---
booktitle: 'Proceedings of the 1st ECAI Workshop on "Machine Learning Meets Differential
  Equations: From Theory to Applications"'
shortname: ML-DEWorkshop2024
volume: '255'
year: '2024'
start: &1 2024-10-20
end: 2024-10-20
published: 2024-10-06
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLDE2024
month: 0
cycles: false
bibtex_editor: Coelho, Cec\'{\i}lia and Zimmering, Bernd and Costa, M. Fernanda P.
  and Ferr\'{a}s, Lu\'{\i}s L. and Niggemann, Oliver
editor:
- given: Cecı́lia
  family: Coelho
- given: Bernd
  family: Zimmering
- given: M. Fernanda P.
  family: Costa
- given: Luı́s L.
  family: Ferrás
- given: Oliver
  family: Niggemann
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st ECAI Workshop on "Machine Learning Meets Differential Equations: From Theory to Applications"
    Held in Santiago de Compostela, Spain on 20 October 2024

  Published as Volume 255 by the Proceedings of Machine Learning Research on 06 October 2024.

  Volume Edited by:
    Cecı́lia Coelho
    Bernd Zimmering
    M. Fernanda P. Costa
    Luı́s L. Ferrás
    Oliver Niggemann

  Series Editors:
    Neil D. Lawrence
date_str: 20 Oct
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v255"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v255
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v255
email: ''
conference:
  name: !binary |-
    MXN0IEVDQUkgV29ya3Nob3Agb24g4oCcTWFjaGluZSBMZWFybmluZyBNZWV0cyBEaWZmZXJlbnRpYWwgRXF1YXRpb25zOiBGcm9tIFRoZW9yeSB0byBBcHBsaWNhdGlvbnPigJ0=
  url: https://mlde-ecai-2024.github.io
  location: Santiago de Compostela, Spain
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v255/mlde24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v255/mlde24.bib
